/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { MockVerifier, MockVerifierInterface } from "../MockVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "_alwaysValid",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "alwaysValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "_valid",
        type: "bool",
      },
    ],
    name: "setAlwaysValid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[3]",
        name: "",
        type: "uint256[3]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516101ff3803806101ff83398101604081905261002f91610045565b6000805460ff191691151591909117905561006e565b60006020828403121561005757600080fd5b8151801515811461006757600080fd5b9392505050565b6101828061007d6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806311479fea146100465780633b4b1a3e14610076578063c608022214610083575b600080fd5b6100626100543660046100bd565b60005460ff16949350505050565b604051901515815260200160405180910390f35b6000546100629060ff1681565b6100a4610091366004610123565b6000805460ff1916911515919091179055565b005b80604081018310156100b757600080fd5b92915050565b6000806000806101608086880312156100d557600080fd5b6100df87876100a6565b945060c08601878111156100f257600080fd5b60408701945061010288826100a6565b93505086818701111561011457600080fd5b50929591945092610100019150565b60006020828403121561013557600080fd5b8135801515811461014557600080fd5b939250505056fea2646970667358221220a2627a8b41a3d55be0d26f89224afa4a3f4d950c44b5d4718923b0866cda506a64736f6c63430008180033";

type MockVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockVerifier__factory extends ContractFactory {
  constructor(...args: MockVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _alwaysValid: boolean,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_alwaysValid, overrides || {});
  }
  override deploy(
    _alwaysValid: boolean,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_alwaysValid, overrides || {}) as Promise<
      MockVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockVerifier__factory {
    return super.connect(runner) as MockVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockVerifierInterface {
    return new Interface(_abi) as MockVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockVerifier {
    return new Contract(address, _abi, runner) as unknown as MockVerifier;
  }
}
