/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as solvencyProofRegistrySol from "./SolvencyProofRegistry.sol";
export type { solvencyProofRegistrySol };
export type { MockVerifier } from "./MockVerifier";
export type { Placeholder } from "./Placeholder";
export * as factories from "./factories";
export { MockVerifier__factory } from "./factories/MockVerifier__factory";
export { Placeholder__factory } from "./factories/Placeholder__factory";
export type { IGroth16Verifier } from "./SolvencyProofRegistry.sol/IGroth16Verifier";
export { IGroth16Verifier__factory } from "./factories/SolvencyProofRegistry.sol/IGroth16Verifier__factory";
export type { SolvencyProofRegistry } from "./SolvencyProofRegistry.sol/SolvencyProofRegistry";
export { SolvencyProofRegistry__factory } from "./factories/SolvencyProofRegistry.sol/SolvencyProofRegistry__factory";
