/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SolvencyProofRegistry {
  export type SolvencyProofStruct = {
    epochId: BytesLike;
    liabilitiesRoot: BytesLike;
    reservesTotal: BigNumberish;
    timestamp: BigNumberish;
    submitter: AddressLike;
    verified: boolean;
  };

  export type SolvencyProofStructOutput = [
    epochId: string,
    liabilitiesRoot: string,
    reservesTotal: bigint,
    timestamp: bigint,
    submitter: string,
    verified: boolean
  ] & {
    epochId: string;
    liabilitiesRoot: string;
    reservesTotal: bigint;
    timestamp: bigint;
    submitter: string;
    verified: boolean;
  };
}

export interface SolvencyProofRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "epochIds"
      | "getEpochCount"
      | "getLatestEpoch"
      | "getProof"
      | "isEpochVerified"
      | "owner"
      | "proofs"
      | "setVerifier"
      | "submitProof"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "SolvencyProved" | "VerifierUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "epochIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEpochCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getProof", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isEpochVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "proofs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(functionFragment: "epochIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEpochCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEpochVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proofs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace SolvencyProvedEvent {
  export type InputTuple = [
    epochId: BytesLike,
    liabilitiesRoot: BytesLike,
    reservesTotal: BigNumberish,
    timestamp: BigNumberish,
    submitter: AddressLike
  ];
  export type OutputTuple = [
    epochId: string,
    liabilitiesRoot: string,
    reservesTotal: bigint,
    timestamp: bigint,
    submitter: string
  ];
  export interface OutputObject {
    epochId: string;
    liabilitiesRoot: string;
    reservesTotal: bigint;
    timestamp: bigint;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierUpdatedEvent {
  export type InputTuple = [oldVerifier: AddressLike, newVerifier: AddressLike];
  export type OutputTuple = [oldVerifier: string, newVerifier: string];
  export interface OutputObject {
    oldVerifier: string;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SolvencyProofRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SolvencyProofRegistry;
  waitForDeployment(): Promise<this>;

  interface: SolvencyProofRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  epochIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEpochCount: TypedContractMethod<[], [bigint], "view">;

  getLatestEpoch: TypedContractMethod<[], [string], "view">;

  getProof: TypedContractMethod<
    [epochId: BytesLike],
    [SolvencyProofRegistry.SolvencyProofStructOutput],
    "view"
  >;

  isEpochVerified: TypedContractMethod<[epochId: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proofs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, boolean] & {
        epochId: string;
        liabilitiesRoot: string;
        reservesTotal: bigint;
        timestamp: bigint;
        submitter: string;
        verified: boolean;
      }
    ],
    "view"
  >;

  setVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  submitProof: TypedContractMethod<
    [
      epochId: BytesLike,
      liabilitiesRoot: BytesLike,
      reservesTotal: BigNumberish,
      _pA: [BigNumberish, BigNumberish],
      _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _pC: [BigNumberish, BigNumberish]
    ],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "epochIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEpochCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestEpoch"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [epochId: BytesLike],
    [SolvencyProofRegistry.SolvencyProofStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEpochVerified"
  ): TypedContractMethod<[epochId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proofs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, boolean] & {
        epochId: string;
        liabilitiesRoot: string;
        reservesTotal: bigint;
        timestamp: bigint;
        submitter: string;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [
      epochId: BytesLike,
      liabilitiesRoot: BytesLike,
      reservesTotal: BigNumberish,
      _pA: [BigNumberish, BigNumberish],
      _pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      _pC: [BigNumberish, BigNumberish]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "SolvencyProved"
  ): TypedContractEvent<
    SolvencyProvedEvent.InputTuple,
    SolvencyProvedEvent.OutputTuple,
    SolvencyProvedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierUpdated"
  ): TypedContractEvent<
    VerifierUpdatedEvent.InputTuple,
    VerifierUpdatedEvent.OutputTuple,
    VerifierUpdatedEvent.OutputObject
  >;

  filters: {
    "SolvencyProved(bytes32,bytes32,uint256,uint256,address)": TypedContractEvent<
      SolvencyProvedEvent.InputTuple,
      SolvencyProvedEvent.OutputTuple,
      SolvencyProvedEvent.OutputObject
    >;
    SolvencyProved: TypedContractEvent<
      SolvencyProvedEvent.InputTuple,
      SolvencyProvedEvent.OutputTuple,
      SolvencyProvedEvent.OutputObject
    >;

    "VerifierUpdated(address,address)": TypedContractEvent<
      VerifierUpdatedEvent.InputTuple,
      VerifierUpdatedEvent.OutputTuple,
      VerifierUpdatedEvent.OutputObject
    >;
    VerifierUpdated: TypedContractEvent<
      VerifierUpdatedEvent.InputTuple,
      VerifierUpdatedEvent.OutputTuple,
      VerifierUpdatedEvent.OutputObject
    >;
  };
}
